[package]
name = "synapse-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-trait = "0.1"
dirs = "6.0.0"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["rt", "macros"] }
toml = "0.9.8"
